# .github/workflows/lint.yml
name: Lint and Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install black pylint flake8 isort

      - name: Run Black
        run: black --check .

      - name: Run Pylint
        run: pylint custom_components

      - name: Run Flake8
        run: flake8 custom_components

      - name: Run isort
        run: isort --check --diff .
